language: python
os: windows
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - os: windows
      language: sh
      python: "3.x"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest